// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoY-SYPIYJI6Wnh-Ht5cTzmtkxcZp5saM',
    appId: '1:439254978016:web:08e4b0d668d80643e2ef85',
    messagingSenderId: '439254978016',
    projectId: 'swe6301group3',
    authDomain: 'swe6301group3.firebaseapp.com',
    storageBucket: 'swe6301group3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBprkk4plHpM7PvIzL4-4Pgl7ruxvWKF7M',
    appId: '1:439254978016:android:59e6c4bcb388be09e2ef85',
    messagingSenderId: '439254978016',
    projectId: 'swe6301group3',
    storageBucket: 'swe6301group3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoY-SYPIYJI6Wnh-Ht5cTzmtkxcZp5saM',
    appId: '1:439254978016:web:52599d5defe4a292e2ef85',
    messagingSenderId: '439254978016',
    projectId: 'swe6301group3',
    authDomain: 'swe6301group3.firebaseapp.com',
    storageBucket: 'swe6301group3.firebasestorage.app',
  );
}
